name: Generate Doxygen Files for RZN DSAG projects

on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Doxygen
              run: sudo apt-get install doxygen
            - name: Check Directory
              run: ls -al
            - name: Generate Doxygen Documentation
              run: doxygen Doxygen/Doxyfile
            - name: Deploy
              uses: DenverCoder1/doxygen-github-pages-action@v1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: gh-pages
                folder: docs/html
