name: Generate Doxygen Files for RZN DSAG projects

on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              folder: Doxygen/Generated
              config_file: Doxyfile
              branch: gh-pages
