name: Doxygen Github Pages Deploy Action

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: DenverCoder/doxygen-github-pages-action@v1.3.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  folder: DSAG/Doxygen/Generated
                  config: Doxyfile
