name: Generate Doxygen Files for RZN DSAG projects

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: mattonotmitt/doxygen-action@v1.9.5
              with:
                  working-directory: './DSAG/'
                  doxyfile-path: './Doxygen/Doxyfile'
                  additional-packages: font-fira-code